name: pangolin
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - biopython>=1.74
  - minimap2>=2.16
  - pip=19.3.1
  - python>=3.7
  - snakemake-minimal=7.24.0
  - gofasta
  - ucsc-fatovcf>=426
  - usher>=0.5.4,<=0.6.3
  - git-lfs
  - pip:
    - git+https://github.com/cov-lineages/pangolin-data.git
    - git+https://github.com/cov-lineages/scorpio.git
    - git+https://github.com/cov-lineages/constellations.git

