name: pangolin
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - biopython>=1.74
  - minimap2>=2.16
  - pip=19.3.1
  - python>=3.7
  - snakemake-minimal<=6.8.0
  - gofasta
  - pysam==0.16.0.1
  - ucsc-fatovcf>=426
  - usher>=0.3.2
  - pip:
    - git+https://github.com/cov-lineages/pangoLEARN.git
    - git+https://github.com/cov-lineages/scorpio.git
    - git+https://github.com/cov-lineages/constellations.git
    - git+https://github.com/cov-lineages/pango-designation.git

