name: pangolin
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - biopython=1.74
  - iqtree
  - mafft
  - iqtree<2
  - pip=19.3.1
  - python=3.6
  - snakemake-minimal=5.13
  - pip:
    - pandas==1.0.1
    - pytools==2020.1
    - dendropy>=4.4.0
    - git+https://github.com/hCoV-2019/lineages.git
